apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VSko45XwzMFrsVB+RB687G2JfcP4bsqnGzsBjBloEVndDAb8Jz5LBQ==,iv:nqqN2Uo9k0aFoMe9b43mxXneBWrefnzPEA7UNwa5zAE=,tag:qkGCsTHVg03uwQHr80ZJGw==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQ3c2cFR2Zk03Z3RXWHVT
        aHpSdnI2WVliQWZXS2ZRUzY1NXcySlVIQTFJCjgxdHlZVjRhTlpVRmwzOGcwUG9V
        UG1HWkl2YXoxSDJxUTE5QWNzclU1ZmcKLS0tIE1OMHNkOGZQa3gwTTh2eGJoaS9y
        T0ZoclhSZHdyNU9JMm9YWUFuSjlRd0UKaRRgd97h/Iv4LLND+ftUULmNiHBmtfUn
        w29wgF7We29Pza80wOZccozrIoqJgdzWbZs4PcDBFRR1OyIFF1Euzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T10:45:46Z"
  mac: ENC[AES256_GCM,data:xE+MudsmuqAsYd+bOlRjjrQ390MHRgxxYQ5T5XqvaCH825uXbOY4bcQKeGj+xmqUPu3HLCQex9O4I/rIZTd0Kbe/dCRb+VNOMjPjUwXtQ8buFHksYyzm6gXYRfaaFVodW8CZ6cklggPeas47o8KG9xNTtvVIlJGOck6DLkIL5Sc=,iv:XRP4mCWvCURATeyrR+1HAiPMljg2tagkS5fGSmvy3eg=,tag:dkVLh3ITRdA1SqBdu2Jk2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
