apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:AWQ8FPjHsjn3zr4limntGK5mvojWFvH2HCfvASCBipIXTDpm0EHlJQ==,iv:k8urOjhZNvn0drTbXgkG/M7MWAJt1/Z1A4eUeosGIDk=,tag:eXrwG6OeTf5OmVdFmTPYuA==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWDRTSms5Qy9FZFRvOGow
        aWZ1ZlhsTHJoRXpOeURKOEJ0dmpFWmV4U0MwCjQ5VUt6VkZ0STdHSDUySDhuRXov
        cFdrWWVnYnZ0a3lxcnQvdksraEk4VE0KLS0tIHUzNHEwK2tLSG1LaEpHYVEvSVNV
        NHo5dnk4WkVDOGppL1VjWUxlSWtQdDQKHs6m09dXcCThDozMCX1eKzoDXOlAJ8R9
        RiaHwCWwBu/jC2BSnp3kR1LX59WcXMdD35y/LQQJXlxdRi3FcdU03A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T10:46:59Z"
  mac: ENC[AES256_GCM,data:amDxeTkkTCJI0eGF3gmcmEAxNV0zb0J/1VMjcuQBEuwkBk+dNhSoiipPW3j/AScvTUu2s0x0U6R70G5cvjLiKoYuQu7aehK1Y6ajs4ZLRPbwClDAzzIu5RsF8/dsB/Ur5islPOoSsIzHqbK+g4OabFXhaM8KRQum96/zOmTuv4E=,iv:G90rQEn3f9fcfKPRX+OGrsoBKtzct57wRClDl5hgf5A=,tag:eLB+E7mZi5ZmxfOyv+jpOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
