apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:F4EE57EMOsgWGhj7CHQhanfn1qrFSoszqIR4yLWRbJJIL6U4eoMCsQ==,iv:Z9RnXxKUQLGqYXjjU5eUvMdHuCKrGv5ECAVeyoQZvcw=,tag:zJrWFXCVMuBcscQpJYEV7Q==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1STZjcEZMTW1Ja21GdHEz
        dDYyZnc2SnVUZFpRbEl6SUhORnI5NVB4OW1NCnl1VzIyT051aXhnaUw4K2wwaUxJ
        WkFuTDlOU3UzUDdsR1RBSllSQTczK00KLS0tIHNJZDY5RDJsSTZlWmphcmZQVEpz
        VDRva2Vlc2JTUTlMeUFIeEhMcWs4VUkKH2Em5vxv2/tUgW8jNXC19sZOe3CanXUS
        iM7LRubbsrUhLv3Tf9995CUELDnh6WLI/nPY1wEo/vEKBvo755Jqew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T14:12:24Z"
  mac: ENC[AES256_GCM,data:Q0wIPKp0xgDiwq7a/1edZRDoeOvysBdhmbPKxl3XmxExw87UUIlc1xsxsVmx4oT6xV/wurPQePxAnAga18XyAWdEzWwOfK59kQxelqqcyOL75hSz7LBpNoH0DVn8mhI1Jk3g5xk5xAxz5T2MZ8RJunbw/SwQsXZdBK4U56ZzxC8=,iv:dvrtiXGSsQVtH9ChOcs67vOBB/vX0x9Fd80iO1B/Xg4=,tag:iWpkD/h3UtETQw4z5tUv1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
