apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6iM2Lz5Dt6r+fA==,iv:7j/k8QOoS1EXxkpAvpEoS7RSktTINse8RiBpND2znWo=,tag:Xsx27yrcAYvm/pi8Q8wFAA==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS09YRE43ME1NdWpTOXo5
        ZlEvN28rRlA1ZkFzVnNhTzVXOWxtMUNaNzJNCjZnc09IMThqT3FwL0lTRU1WQnIx
        dkZ0VnJEYmZjUG40VU1CWlV2VWl4bkUKLS0tIEk2bTdNclMrL0p2UEJHQ3RWcWdL
        UmUwYjJ6cXhZWlFlOXlwOFZ5Z1FNVTgKGpyLbOabl5dFE7eAbHfO61sGeTJLWE7z
        l4x2iSwcXmzzIWaIpz9OeqaRSWvvxOAA4XFevqZf3/4IoODiivXrGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T10:45:46Z"
  mac: ENC[AES256_GCM,data:GArEV+2eVirq8GhnrT57+hS9XD4vfjyT2FkuRKqFnL1wLJq+uyN8oG8raqQ7WK2Rv9yOQmE/UeOUnzoI81rLEponb+bjP6Y/uUIUI7wXmUq1YfMBf3f3ccbOU4p0ik+kqbM1tVfkHWx1qZ5nf4p4MhO00HFSCpYd/IUkwFmmAsc=,iv:FR6nzTP8cj7rfS18sFQG0NOZy05V1rXHyxt4ighJqRQ=,tag:dyb3e/ub6G5zUMWqfzxwsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
