apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kAwTNO1bXA33/A==,iv:SHkgpGBISu+hDb1xLQi1zogzIl5y2Q97CMcn7szaxSs=,tag:GHGSWZQOgJdtWLAIfKUfKw==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNThTMHlyTFpjNnYxejR2
        MkxYWTNZanBNVmplMHNKbWN1T0dnQUFWTW1zCklCL2xMOHZZTWg1cVdMaitnZTBF
        amhNeHd1OTIxY0tTeVQ4ZFpNdDM1SW8KLS0tIE5adlBDQ1UwQkdmdUlya1h5TXVE
        WUp0ZnhlUy9YRlp5bVRyc3dEcTl3S2sKp9fdGEj+xwLryB1ayD1MwcDU017WOgYF
        32s4x/t8NJ7nI60CRVXiRsraJcmkgnxqE0QlC0PZR8QzL7HpdJXDQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T10:46:59Z"
  mac: ENC[AES256_GCM,data:ln9fcEL6mdXBgJ22UjctaZatU+MVq+Zv9U4v83R90b7kcTqpoDZlDn1eYjAOp/GV7BZWt8dOZTHgxDWpIhDFg87H4IJhPFzgXLH5lvZZVGsmlIxjkhQGiI6u4V0Gr1gX/41kryFjsEd+wLjPBaRosPwAIrGJj8xvRFLT/bsLFVU=,iv:VUbGT/mBJD4J5bt32oGpTYOSdD/aU8jmhFYCpyiPI5k=,tag:I0gOcyEXEskx3ZnXOWjYnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
