apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:mFtj+rc9XgFEerv8ktmJrbwuGeK/toZTEr3zD7m2LVo=,iv:osiJUmJhafO6bdwqOwHQSNKPZhjhS+j6KYEFQRt6ykw=,tag:23bSxqlZ4RSumyv0f1CIJw==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZk85bUVqZFJZNU9jTUhB
        SGRZdmZ3T0tqWGJHblAzb0FnTUZ5YThKc0ZrCitTcGJCYnZPMi9LVzFsdWt6U3Iz
        bGxhbktselBpY1VDKzlXbTZmRGRWZ00KLS0tIG1LMVA3dTY3cHdRMzJjOSszK0Vt
        NWJOMUF4Tk5Vdjg5MVAwN2RkUUNjTzQKHceDXRQru92rvJ1F7geHXqNsyEhbbOaP
        FvdrqxVdgyuKgSO5taEDhF22+/aNjvq8Wljb8RrknXHohdA2HIwu0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T10:45:46Z"
  mac: ENC[AES256_GCM,data:FdXflzHfxmAeTABGRFdqoa7Hljg/phB+7pKZZojFyFSt2vYDOG364Hm/3mqhOxwCyZgQixkC8mUlIMNYgWCPrgaZBmL681Y0HtYMZKAODYHvgsM+AGu+rzFHx1O01711OpYMO5F/ULgQ07lY41yk4lb0HCeTnfSa030imZ053Xg=,iv:/mTM9+h+Vt61IQ7eG/wSoJpmy7J2iSjFxNVEPJK/QQY=,tag:TPgsV/f0y48h2f4UpE5ymw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
