apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:sNoi5Nh9N9o/V225k1gBgR7sA8gtC4l18e3QtYVhqkk=,iv:FdkEueBP93mLEu1s9b5dpNcf3I8viXzu4C1vlllvcJ8=,tag:FznjSikTtmCzxr+YjSV0jA==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrd0NxenNwYzhIMThOVmhL
        dExkeWZJQmdzN29KUGVQZDdxZkxmb2h2QnprCkk4MWRkNm5nQ2lRSTRXYWN2L3Jj
        S3Z6UjEyN3dIU3kyVHJiemt5N1JJazQKLS0tIDY2YWMrMmFNM1FnNUxldEluVUxu
        Q05WSTVnbEZBa2Y2eTdPYjNRd25idVkKSsHlPKuHER32dh1TErqQ4oXz1/30vTMo
        yYAarrd/SE1hzbg9sr557oKoLUDqXnxzE2VZewUXslqMWaoiVGShXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T10:46:59Z"
  mac: ENC[AES256_GCM,data:uyFsEvzqxVKdGhRkzNbni9BCLwa6ham0hHpxkWkt0ZQwy7l/8Kv7mUrpPLUyJlgxcnsZ75rf5vUhljfo6J7cXda8VowXneqqJTS1txeRaM/t9to64pZCLVwXt7Jt6x3XzjFMJnR71yAAMzOmuPsXHy0rluLOr57HCs9qxMa+bJE=,iv:628kYKm+TR64m1mKtohytul/zAHnAz5u/BEjNWcDNBY=,tag:RnMIil1JemauQTnephKZqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
