apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Xg3eZe3v1hPvorceJI+s/AO6iUHnU0/E3IZTFrjJLYa7N2oLJfaWTYL5yjILzIQncPNSw7dMmbFqHzFytDXW34/guoZ1eOqrT28xevklX/e7Hmkv93gx8lOlUF6I0ykNWTAQt1cZcY1xq93ke+g5UIWpSOBn/dXr8I23WCItymgA1CxCDog/pBpbC63TVedmalrOJXHZ77TKNUMmvNpMTqwlJWYNcW28PVBjkHz5INIwOfVs,iv:R1dKEZlT8lW+dGRmlwBRTYvp2xtD6l2cPrY3TOeIsSA=,tag:cqyQuDtYGLCESvEVXTH2VQ==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ3hIeUZmeFJXSlVGN1V4
        VHEwWjZPMnV2eGJOUDIzQTgvQm1XVlhVVGdFCkhwWVVLRGlKRDRyQ2NrY21lLzdx
        dlljUUFIOElPSjBobDN3V0V4YnZFSzAKLS0tIFgxNVRoUFV3NlRBellKanpBQlVk
        dTBNeUlZUWlMR3c1bUNhVFA3d0ZYZTAK14xaXRmG0jfMd5IIksS8ZQ90eAnPRltF
        dFTotQFTlFaZC0IV9TvRmZRxgPkm3yEiuICYZdfob5Gz4sVJxxiaTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T14:12:37Z"
  mac: ENC[AES256_GCM,data:VSL+SYxBZk/PHPoSY8iYmWvFIdJcshMRM5jfShdKaitwZPasKWX7CkPNRtE0b7SqhghtljCqvBnKJuR2CFEDkh/8UeWobgAd65BbgA6bpzDV/2qkEqGxi0qGjKM8glC8ovLXHN8Bpo/FCQudZkBBGYvebxI5x915/e7raBPwm60=,iv:V/I8cAHtCXsU7Aw7uAk+liC09Pc2TlMZo8xKl0pjpxM=,tag:9DoGEnFS8yRO3bgOR4tmaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
