apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GRSzoOacVTCIG3bEkpbcZ7MY/cmVdWrcoFlYsDFFC4BVsh5ib73pGsywy4bgT5qKo63vWKOJn0oOatx5ljn8YJnZH86t1zFHdgt1Qz1p5Sq/zXdUhcE3i3Lg1p7qTQt/wuli9NHhrSkY3XdnKJbvpYQAqvkiQuOQTC9E0/S7GRvGiiKDEgiBCsZWzZlvy6JnK2dEMTD5u9/mCYtMHvVe4LoWVMRs8V3hYK+4VgAbPpSBTm7x,iv:lYi6gZCISUoT/NBOD41nF2LXbb8ivR9Al7kJ235VwZU=,tag:xP7HOmvdmIlQvNlHzid+Nw==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMEdvcTdZSXJZOWVPYkds
        TTZzSHV3NTUyMTFVVFpjQStETElrc2o0VDJFCnU0ZzhpWlBCTGwvV3RJMEh0Yk9h
        WGdXc3oxdmlaVlZ4dHZKb21yQ1J0L00KLS0tIHFIajIwZ1JlZU5GS2VWdFVndDNm
        U2pWZU40VFY1dS9Ga1hvU3p2SlYwWEUK1SfeNvNYlqXDAH7oxkv6Xkgo3yFEhZUf
        p2FidWEvR+KxqCxPC1Y2sNTXbYWl7p/3scENJOLELBh/H+SRWWdK0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T10:46:59Z"
  mac: ENC[AES256_GCM,data:78KGRnF2q1LF0fIJXGoiUG4Mi8rnkAdZ3NJp1Eb/G6jJgPB5XzA0rFy1+5/9rFGUnBksl4x3epktqVVrM5BmnxF5liN/V7Sp2w5TuwB3Q9cFAbguuoZTh36wADesEAQyFdriNEGfOeGP0Fs2SCCiSLEPP2Xx41ckNWda2aS2pEw=,iv:HbUC3qGM+QJKqqzylAhA4OLqYt0M9K2kIm2kfPc7+Hk=,tag:1PyjSKvzc4vwf1CQuek47A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
