apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:K6FL5F+lweyhmLC/cr/uY/2RGhdH6Q2efRuj8sMzjSkHv8yw2sHICLc2gS+wqQU4b6eqQT9RQd85t2lunQA+/VZUDpq8W/0fhi62Y61dmBxExAcM5xieD5bbtVCS5gUZo3RJA2htim445eiE/YXa2RZb8TVUpXTBM7Ujv/IvIFTUeD9DUXZdsaydVH73Ck7V/5PnUZiTyMpW1zTl0jscoiqe5vjQjTA6XB4to9eli6PEAZ7l,iv:AcCpuesGAh5NdVnpPHZ8GLWlLfqEQjydcYG2SzYpgQw=,tag:4paVV1rXH4g6dxKk7dZSWw==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSV3FkMFpZVENaK1VVd1I3
        S21ZN0JkK1g2TTA5UzI0TnZPTnBERVZ6eVV3CkI3RGF4bXNhd0tNRzh4ZmtkN2lm
        dUVscU5kVURycEoyWDFsOVdlMTgrZEkKLS0tIE0zYzZSOUlGcmY3SXFTNHIweXM5
        empFMFc0T3crcUhBL2lSNWloWStYeFkKb67czGy9YmepFvDfZS1lM3fibp/26LZ9
        Jfmg0IbKtGgLpYdBLNf6/3JXWs5OWpvLrkznT+O1hUMxhnkH2ilH0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T10:45:46Z"
  mac: ENC[AES256_GCM,data:EY76A7sQ9yg9BMatUb6q0JnHggYyKpBMyxrZMvQ9c7wOJ5L9XASk0O5WJqPHmEtdDyyrpflJpfe0G/S3H8t0APSHUgEXADQrdp01CQfEo9o8K5C1f6wPTL7inyS6TO+VXhu5q6M55kTe/IrANT6pclG/7FuFTRE3OZXN9Y+xSy0=,iv:gLNl2BNlttuJWn4TJt+yqpw8RFIJFnK50FG7asB78Xo=,tag:DuN9CcuGOIpVk1IbNBuAcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
