apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:tVrISwxkO5nwJnTwaUVC7hTTYyIELOJQjyub5gjY+K3ktYp6QnwUDw==,iv:GdFnLt6p8YZErUPZhg/bFAjnrD/8RNaaYJd+BnuliXM=,tag:cogyxMIVCuQEKYgYJ1PAlQ==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc3gwRksrcWErZUFXaTcw
        SDBUOXp5d1lyTGxoZnRlSlFPT3FQTy9ZY2o4CkVFMnZKOUN1U2U1UFBxVmdGclBY
        dFhJZWNibEFRckUrbkFIUFVObFdGNzAKLS0tIEhWRjZCS296VzVJbThwZTVicGZ3
        UnNOaFd1WVhFY3ZhV2dtTXBHNFBiOUUKH+Up2auw1v76oh5QXC/gqV3mvEhRO2y+
        qLnlG1BDAkyfbBX6uym9Sin0JtFjmUIDWNT0U9dEaOChgo8q01bLxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T14:48:01Z"
  mac: ENC[AES256_GCM,data:oggqx5tvxhe0nvs/ArmgdUtE7oN76ohfUFNGLtv0oZKxBVi7iC3WyltX6Tivr45HuDxmYh4lYiE0xiYQ+SAZDyXydD1GY/3I1oTdWcCoOrdqh9FWxntiHOPULOuUv41UqucXUtUMpkjKhHu7Bp1lyhgM/LFh3yz4z0gNiKf5QMk=,iv:F8NUQ5yHwQO8K5tdhg+GpkU74gIdfklJDwybqv9IBiI=,tag:syBLNmUAKI3u+zQKC0C3lA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
