apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:/Krx5ZiXcNn2hTZRKGiren5EQ/tLcTrzP6RQb0Ai2o2T8Br78yZmcQ==,iv:POvulDr+HMohP8V5y6dwVN4HsUMf/8FE+Zskm/Q5vCo=,tag:PzqZWW0k5mF0hbQhbRDcHA==,type:str]
sops:
  age:
    - recipient: age135za6lghfdp6w5cmr6ef9jyclt87jzfq3j3948rgj9g4d5nr8czs98rwfp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd3ErbEFSczhvajk0dWJI
        WXRQdzRDSUZDcUlpVkVvdHpoa2x1ZE5lVkVNCng5dVorK0lKaVFxZDJKbE9ZMWxz
        MEJwb284YmtMV0Q1a2Q1a0I4VGNRK2MKLS0tIEljMHZjZEtyMXdhcUo5YXkreUtw
        Wlg1MlFUbkJPRkxoV3FqcjhpaVVSWTAKl6aQUDU+OiodJg4oLBDwia4ScLChnuK7
        Vx8IHDduLxWqdhVeFczvHIltVGhv66QHdD6i0w7FGSVWFDQz1+eceQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T10:45:46Z"
  mac: ENC[AES256_GCM,data:0mRWwdgWrnB/pBdsJjw3efZE90LcJ7d8W9UekLfATabg+0mgKW34/h+v0B6qcxCTBElwyGl9WkJDRXzHIwpQS8trq9DreXl3oJRru7wtUrjWRDYgU896jXQXl1sBB/L7+6ZtNI5hPBgoupFd/ycejfiIGBQkyTx9FIw1Bn7N97c=,iv:dOUXBznf3l8HvYdNL31IbaOIIT/kXoKDnf/z24/Oo4M=,tag:9SI7MraePmPHkwVvsY/x4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
