name: Actions Runner Demo
on:
  workflow_dispatch:

jobs:
  Test-Actions:
    runs-on: arc-calvinz360-home-ops
    steps:
    - run: |
        echo "this is working" > /mnt/data/test.txt
        cat /mnt/data/test.txt